# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
PASSWORD_KEY: V\x8B\xE1\"R%4\x94p\v9\x84\xAF\xF2\r9\"\xBEf\xDB\bn\xCD\xE9\xC81/\xE0\x13Af\xE6

COURSE_KEY: \x9D\x06\xB1k\xBC\\}\xAF\x88dl\xF9s\xFCz;\xD7\xADip\xC6\"\x82\x83\xD4$\x1Cpr\xAE\x17\x01

SECTION_KEY: 6\xEE\xAD\x81\xA3\x14\xA0\xCC\x83\x04\x9F\xD3\xCA\x9C&\x91^\xD3}\x1C\x14\x8DA\xA1\x16\xFC5\xEF\xB3\xB2C\xD6 